-- Auto-generated by scripts/clean_data.py. Do not hand-edit; re-run the script instead.

insert into languages (code, name, is_default) values
  ('en', 'English', true),
  ('pcm', 'Nigerian Pidgin', false)
on conflict (code) do nothing;

insert into topics (slug, name) values
  ('malaria', 'Malaria'),
  ('maternal-health', 'Maternal Health'),
  ('nutrition', 'Nutrition'),
  ('hygiene', 'Hygiene'),
  ('clean-water', 'Clean Water'),
  ('first-aid', 'First Aid'),
  ('immunisation', 'Immunisation'),
  ('family-planning', 'Family Planning')
on conflict (slug) do nothing;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'sleeping-under-a-treated-net-1', 'published',
    'A. Bello', '2025-01-04', ARRAY[1]
  from topics where slug = 'malaria'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Sleeping under a treated net', NULL, 'Sleep under an insecticide-treated net every night to prevent malaria, especially children and pregnant women.' from new_article
union all
select id, 'pcm', 'Sleep under net wey dem treat', NULL, 'Make you sleep under insecticide-treated net every night to stop malaria, especially pikin and pregnant woman.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'malaria-prevention-2', 'published',
    NULL, '2025-01-04', ARRAY[2]
  from topics where slug = 'malaria'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Malaria prevention', 'Simple steps to avoid malaria', '<p>Use treated nets, clear stagnant water, and see a clinic early if you have fever.</p>' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'clearing-stagnant-water-3', 'published',
    'A. Bello', '2025-01-01', ARRAY[3]
  from topics where slug = 'malaria'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Clearing stagnant water', 'Mosquitoes breed in still water', 'Empty containers and clear gutters so mosquitoes cannot breed near your home.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'antenatal-visits-4', 'published',
    'N. Okoro', '2024-11-30', ARRAY[4,5]
  from topics where slug = 'maternal-health'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Antenatal visits', 'Why to attend antenatal care', 'Attend antenatal check-ups at least four times during pregnancy to keep mother and baby healthy.' from new_article
union all
select id, 'pcm', 'Antenatal visit', NULL, 'Go clinic for antenatal check-up at least four times when you dey pregnant so mama and pikin go dey healthy.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'eating-well-on-a-budget-6', 'published',
    NULL, '2025-02-10', ARRAY[6]
  from topics where slug = 'nutrition'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Eating well on a budget', 'Balanced meals with local foods', 'Combine beans, vegetables, and grains for a balanced meal without spending much.' from new_article
union all
select id, 'pcm', 'Chop well without spending plenty money', NULL, 'Mix beans, vegetable and grain make you get balanced food without spending plenty money.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'wash-your-hands-8', 'published',
    NULL, '2025-03-01', ARRAY[8,9,24]
  from topics where slug = 'hygiene'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Wash your hands', 'Handwashing prevents disease', 'Wash your hands with soap and clean water before eating and after using the toilet.' from new_article
union all
select id, 'pcm', 'Wash your hand', NULL, 'Wash your hand with soap and clean water before you chop and after you use toilet.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'safe-drinking-water-10', 'published',
    'I. Musa', '2025-03-15', ARRAY[10]
  from topics where slug = 'clean-water'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Safe drinking water', 'Make water safe to drink', 'Boil or treat water before drinking if you are not sure it is clean.' from new_article
union all
select id, 'pcm', 'Water wey safe to drink', NULL, 'Boil or treat water before you drink am if you no sure say e clean.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'typhoid-and-clean-water-11', 'published',
    'I. Musa', '2025-03-15', ARRAY[11]
  from topics where slug = 'clean-water'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Typhoid and clean water', NULL, '<strong>Typhoid</strong> spreads through dirty water and food. Drink safe water and wash food well.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'first-aid-for-burns-12', 'published',
    'Dr. Ade', '2025-04-02', ARRAY[12]
  from topics where slug = 'first-aid'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'First aid for burns', 'What to do for a minor burn', 'Cool a minor burn under running water for about twenty minutes. Do not apply oil or toothpaste.' from new_article
union all
select id, 'pcm', 'First aid for burn', NULL, 'Put small burn under running water for around twenty minutes. No put oil or toothpaste.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'choking-help-13', 'published',
    'Dr. Ade', '2025-04-02', ARRAY[13]
  from topics where slug = 'first-aid'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Choking help', NULL, 'For a choking adult, give firm back blows between the shoulder blades and call for help.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'vaccines-for-children-14', 'published',
    NULL, '2025-04-20', ARRAY[14,15]
  from topics where slug = 'immunisation'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Vaccines for children', 'Keep to the vaccine schedule', 'Take your child for all routine vaccines on time to protect against serious diseases.' from new_article
union all
select id, 'pcm', 'Vaccine for pikin', NULL, 'Carry your pikin go take all the routine vaccine on time to protect am from serious sickness.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'family-planning-options-16', 'published',
    'G. Eze', '2025-05-05', ARRAY[16]
  from topics where slug = 'family-planning'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Family planning options', 'Spacing births safely', 'Talk to a health worker about safe options for spacing your children.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'fever-in-children-17', 'published',
    NULL, '2025-05-06', ARRAY[17]
  from topics where slug = 'malaria'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Fever in children', 'When fever is an emergency', 'If a child has fever with fits, fast breathing or cannot drink, go to a clinic immediately.' from new_article
union all
select id, 'pcm', 'Fever for pikin', NULL, 'If pikin get fever with convulsion, fast breathing, or e no fit drink, carry am go clinic sharp sharp.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'breastfeeding-basics-18', 'published',
    'N. Okoro', '2025-05-10', ARRAY[18]
  from topics where slug = 'maternal-health'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Breastfeeding basics', 'Breastfeed in the first hour', 'Start breastfeeding within the first hour of birth and feed only breast milk for six months.' from new_article
union all
select id, 'pcm', 'Breastfeeding basics', NULL, 'Start to breastfeed within the first hour after birth and give only breast milk for six months.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'diarrhoea-and-ors-19', 'published',
    NULL, '2025-05-10', ARRAY[19]
  from topics where slug = 'hygiene'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Diarrhoea and ors', 'Treat diarrhoea with fluids', 'Give oral rehydration solution (ORS) and continue feeding a child with diarrhoea. Seek help if it does not stop.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'malaria-in-pregnancy-20', 'published',
    'N. Okoro', NULL, ARRAY[20]
  from topics where slug = 'malaria'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Malaria in pregnancy', NULL, 'Pregnant women should sleep under a treated net and take the preventive medicine a clinic gives them.' from new_article
union all
select id, 'pcm', 'Malaria when you dey pregnant', NULL, 'Pregnant woman suppose sleep under treated net and take the medicine wey clinic give for malaria prevention.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'healthy-snacks-for-children-21', 'published',
    'F. Yusuf', '2025-06-01', ARRAY[21]
  from topics where slug = 'nutrition'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Healthy snacks for children', 'Better than sugary snacks', 'Offer fruit, groundnuts or boiled eggs instead of sweets and soft drinks.' from new_article;

with new_article as (
  insert into articles (topic_id, slug, status, author, last_updated, source_row_ids)
  select id, 'clean-cooking-smoke-22', 'published',
    NULL, '2025-06-02', ARRAY[22]
  from topics where slug = 'nutrition'
  returning id
)
insert into article_translations (article_id, language_code, title, summary, body)
select id, 'en', 'Clean cooking & smoke', 'Reduce cooking smoke', 'Cook in a well-ventilated place to reduce smoke that can harm the lungs.' from new_article;
